### ISSUE TITLE
Tether upgrade breaks UglifyJS and other minifiers

### ISSUE THREAD

**Issue by j3tan** [danreeves/react-tether#202]
This isn't really an issue with `react-tether`, but it is useful to track potential issues with version `1.0.4+`.

The dependency upgrade to the latest `tether` introduces a problem with running UglifyJS during webpack prod builds (https://github.com/HubSpot/tether/issues/291). As stated in the related issue, it is actually a bug with the minifiers and not `tether`itself, but that does prevent users from adopting the latest version of `react-tether`. I suggest leaving this issue open for visibility or revert tether to an older version (less ideal).

**Comment by j3tan** [comment]
What a user might see during a prod build:
<img width="655" alt="example-failure-uglify" src="https://user-images.githubusercontent.com/2489149/52366240-1a3abd80-29fe-11e9-9026-8add66ade09b.png">

**Comment by danreeves** [comment]
Thanks for opening this ticket for visibility. 

**To future visitors: it's recommended you move to terser.**
*uglify-js doesn't support ES6+ and uglify-es is deprecated*

https://github.com/terser-js/terser#why-choose-terser
https://github.com/webpack-contrib/terser-webpack-plugin
