### ISSUE TITLE
Component update blurs input

### ISSUE THREAD

**Issue by NilSet** [danreeves/react-tether#203]
Right now whenever the TetherComponent updates, it unconditionally calls `appendChild` with the portal's dom element. If the portal has an input element inside of it, this for some reason makes the input lose focus. This makes it impossible to have a controlled input controlled from outside the TetherComponent.

The demo has been modified to show this behavior at https://github.com/NilSet/react-tether/tree/update-loses-focus

**Comment by danreeves** [comment]
Released in 2.0.1
