### ISSUE TITLE
renderTarget not getting rendered on server in SSR

### ISSUE THREAD

**Issue by reintroducing** [danreeves/react-tether#205]
Hello,
I'm using TetherComponent in an SSR environment and I noticed, when I turned JS off to see my server rendered page, that the `renderTarget` prop and the items its taking are not rendered on the server. Is there a reason for this? I looked at the source and can't seem to figure out why it wouldn't be, but maybe I'm missing something. Here is my code, in case it helps, but I imagine that you'd be able to duplicate this without my code since there isn't anything special about it (plus my code is obviously tailored to the project, but maybe you can spot something in it that I'm missing):

```
<TetherComponent
    key={tetherKey}
    className={tetherClasses}
    attachment="top left"
    targetAttachment="bottom left"
    constraints={[
        {
            to: 'window',
            pin: true
        }
    ]}
    renderTarget={ref => {
        return (
            <span ref={ref}>
                <TextInput
                    ref={node => { this._textInput = node; }}
                    name={name}
                    disabled={disabled}
                    defaultValue={selectedDate}
                    onFocus={this._onInputFocus}
                    icon={(useIcon)
                        ? <Icon name="calendar" />
                        : null
                    }
                    iconPosition="right"
                    autoFocus={autoFocus}
                    focus={focus}
                    placeholder={placeholder}
                    readOnly
                />
            </span>
        );
    }}
    renderElement={ref => {
        return showCalendar && (
            <DatePickerCalendar
                ref={ref}
                className={calendarClassName}
                onChange={this._onDateChange}
                selectedDate={this.state.selectedDate}
                disablePast={disablePast}
                disableBefore={disableBefore}
                disableAfter={disableAfter}
                overrideInitialMonthWithSelected={overrideInitialMonthWithSelected}
            />
        );
    }}
/>
```

This all works fine in the browser, by the way, and there is nothing special about TextInput, its just a wrapper for `input` to add some additional styling for our core UI components look and feel.

**Comment by danreeves** [comment]
Thanks for filing an issue. 

I have a feeling it'll be this line: https://github.com/danreeves/react-tether/blob/master/src/TetherComponent.jsx#L291 and this https://github.com/danreeves/react-tether/blob/master/src/TetherComponent.jsx#L87

We don't have an `_elementParentNode` in our first render so `null` is returned. We probably need an SSR check or to just render the `renderTarget` in the first pass and only render the `renderElement` once we have an `_elementParentNode`

**Comment by designbyadrian** [comment]
I have the same issue for the same reason in a NextJS application.

**Comment by reintroducing** [comment]
@danreeves So I went down the path of looking at this today. I was able to fix it with the line you pinpointed (https://github.com/danreeves/react-tether/blob/master/src/TetherComponent.jsx#L291) and just changing the condition to only check for targetComponent, as in:
```js
if (!targetComponent) {
    return null;
}
```
Nothing broke by removing the `this._elementParentNode` from the check and i'm trying to figure out why its even necessary to be part of that check. What's the reasoning for having it there?

**Comment by reintroducing** [comment]
@danreeves any updates on this? If you even point me in the direction of why that check is necessary, I can try to accommodate in an SSR scenario to fix this issue, but at the moment I'm stumped as to why its even there.

**Comment by reintroducing** [comment]
Don't mean to keep pestering you but this is the only item I have remaining on my SSR TODO list for our (rather large) project and I was hoping to get resolution. If you let me know what else is outstanding above what I've already outlined, I'll be happy to look into it to help push this over the finish line.

**Comment by designbyadrian** [comment]
@reintroducing What if you make a pull request?

**Comment by reintroducing** [comment]
@designbyadrian Before doing that I want to make sure that my change does not break anything else that I'm not anticipating. I'm happy to do so if that is the case but I don't have enough knowledge about the internals of this package to figure that, unfortunately.

**Comment by danreeves** [comment]
Sorry for the slow replies, I've been busy. I can't think of any good reason for the extra check off the top of my head. PR's are extremely welcome!

**Comment by reintroducing** [comment]
PR created

**Comment by reintroducing** [comment]
FYI i'm looking into the test errors right now on that PR.

**Comment by reintroducing** [comment]
Unit tests for the win. I got my question answered as to what would be broken by doing this and was able to circumvent it with the fixes in the PR. It's now updated and the tests pass as they should.

**Comment by danreeves** [comment]
Thanks! LGTM. Published in 2.0.3

**Comment by reintroducing** [comment]
Appreciate it, thanks!

**Comment by reintroducing** [comment]
Just confirming I updated my project with the latest changes and everything seems to be running as expected on the server. Thanks again!

**Comment by danreeves** [comment]
Awesome, glad to hear it
