### ISSUE TITLE
Typescript types definitions are missing "constraints" property

### ISSUE THREAD

**Issue by JabbyPanda** [danreeves/react-tether#209]
`constraints` is very important property of `tether` component, this property usage is even mentioned in the readme of `react-tether` 

https://github.com/danreeves/react-tether/blob/master/README.md#example-usage

**Comment by danreeves** [comment]
Thanks for letting me know.

PRs welcome!

**Comment by danreeves** [comment]
Resolved by #210 

Will be in next release
