### ISSUE TITLE
Cannot pass in React ComponentClass to renderTarget?

### ISSUE THREAD

**Issue by kingller** [danreeves/react-tether#212]
Hi, 
 My Code is as bellow,
```
<Tether
                renderTarget={ref => {
                    return (
                        <MultipleSelector
                            selectorValueList={selectorValueList}
                            placeholder={placeholder}
                            ref={ref}
                        />
                    )
                }}
                ...
/>
```
When I give ref to React ComponentClass `MultipleSelector`, an error happens
```
Uncaught TypeError: Cannot read property 'defaultView' of undefined
```
Do I must change my component to React FunctionComponent, and use `forwardRef` to add the ref to HTMLElement?

**Comment by tensor-flower** [comment]
Same issue. Previously using version 1 with children, now it broke but cannot migrate.

**Comment by tensor-flower** [comment]
Wrapping your component in a div with ref={ref} works for me

**Comment by kingller** [comment]
Thanks. But it will change my component structure, I don't really want to do that, Some places used will cause problems, for Example, add tooltip to a Button which was written by react ComponentClass. The version 1.0.4 has a bug for me, scrollbars sometimes appear in document.body when I first open it, then disappear, page thrashing happened. The reason is that the div added during the first rendering has no style, which causes the scrollbar to appear. How can I fix it if I keep version 1?

**Comment by danreeves** [comment]
Yes, you need to pass the ref to a HTMLElement, whether that's inside the component or wrapped around it. This API change was a requirement to keep working with future React versions & Suspense; the old methods are being deprecated and eventually `getDOMNode` will be too.

If you have react-tether v1 issues feel free to open another ticket.
