### ISSUE TITLE
Can you add a style or class to the tether element div when first rendering in v1

### ISSUE THREAD

**Issue by kingller** [danreeves/react-tether#213]
Hi,
Can you add a style or class to the tether element div when first rendering in v1? It has a bug for me, scrollbars sometimes appear in document.body when I first open it, then disappear, page thrashing happened. The reason is that the div added during the first rendering has no style, which causes the scrollbar to appear.

**Comment by danreeves** [comment]
Hey, I've not noticed this happen before. It'd be great if you could provide a reproduction of the issue for me to investigate

**Comment by kingller** [comment]
Here is my issue [gif demo](https://raw.githubusercontent.com/kingller/gaia/master/images/tether-issue-demo.gif), if need, I will show the reproduction code later

**Comment by kingller** [comment]
Hi @danreeves ,
Here is my code demo [https://codesandbox.io/embed/reverent-water-3he2z](https://codesandbox.io/embed/reverent-water-3he2z) which can reproduction the issue. Please make the height of window be about 510px, you will see the problem.

**Comment by kingller** [comment]
It is caused by the bellow code,
```
componentDidMount() {
    this.inputEl.focus();
}
```
I focus the input in `componentDidMount`.
Now I delay the focus time,
```
import raf from 'raf';

componentDidMount() {
    raf(() => {
        this.inputEl.focus();
    });
}
```
It's OK.
