### ISSUE TITLE
Change RenderProp typing to be more flexible

### ISSUE THREAD

**Issue by leabaertschi** [danreeves/react-tether#220]
Currently the typing for `RenderProp` forces you to have an `HtmlElement` as a root for target and element. We also use a `TetherComponent` with an `SvgElement` as target, which is not possible with the current typings. 
Is there anything speaking against the following typing?

`type RenderProp = (ref: React.RefObject<Element>) => React.ReactNode;`

Or maybe you could even allow any `React.RefObject` so we could also use it directly with custom components without having to wrap them?

**Comment by danreeves** [comment]
Yeah, this seems like a good change

**Comment by leabaertschi** [comment]
Ok, I'll create a PR.

**Comment by danreeves** [comment]
Published in 2.0.7. Thanks so much
