### ISSUE TITLE
Not able to attach Target ref if target inside Child Component

### ISSUE THREAD

**Issue by sudhamab** [danreeves/react-tether#222]
Dear team 

thanks for this super useful library. For simple use cases, we are able to make the lib work. But I am getting some issue in the following scenario where the refTarget is inside a child component, which is a list of items and I am trying to adjust the Tethered element as per which item in the list is clicked. A mock example of what I am trying to do is as follows:

There are 3 classes 

**1. App.js ( only placeholder )**

```
import React from "react";
import ParentComponent from "./ParentComponent";

function App() {
	return (
		<div>
			<ParentComponent />
		</div>
	);
}
export default App;
```

**2. ParentComponent.js**

```
import React from "react";
import SampleList from "./SampleList";
import TetherComponent from "react-tether";

class ParentComponent extends React.Component {
	constructor(props) {
		super(props);
		this.state = {
			clickedItem: null
		};
		this.showItemDetails = this.showItemDetails.bind(this);
	}

	showItemDetails = element => {
		this.setState({
			clickedItem: element
		});
	};

	render() {
		var eventDetails;

		if (this.state.clickedItem) {
			eventDetails = (
				<TetherComponent
					attachment="top left"
					targetAttachment="bottom right"
					
					renderTarget={ref => this.state.clickedItem}
					
					renderElement={ref => (
						<div ref={ref}>
							<h2>Tethered Content</h2>
							<p>A paragraph to accompany the title.</p>
						</div>
					)}
				/>
			);
		}

		return (
			<div>
				{eventDetails}
				<SampleList
					onSelectEvent={this.showItemDetails}
					eventRef={el => (this.state.clickedItem = el)}
				/>
			</div>
		);
	}
}
export default ParentComponent;
```

**3. SampleList.js**
```

import React from "react";

class SampleList extends React.Component {
	constructor(props) {
		super(props);
	}

	renderItem = item => {
		return (
			<div
				onClick={e => this.props.onSelectEvent(e.target)}
				ref={this.props.eventRef}
			>
				<li>{item}</li>
			</div>
		);
	};

	render() {
		const mylist = [...Array(40).keys()];
		return <div>{mylist.map(item => this.renderItem(item))}</div>;
	}
}
export default SampleList;
```

**PROBLEM**

The `this.state.clickedItem` is being detected correctly but I am not able to attached the Element to be Tethered to it because I am somehow not able to associate the ref properly to it. 

I tried many different ways but may be I am missing something 

The UI is fairly simple. Attaching a screenshot for reference.

![Screenshot 2020-02-27 at 6 02 29 PM](https://user-images.githubusercontent.com/8850788/75446877-43721700-598e-11ea-9d92-112844ecef16.png)

How do I associate the ref in the targetRef with the clicked element? 

thanks for your help!

**Comment by danreeves** [comment]
Hi @sudhamab, here's how I would solve it: https://codesandbox.io/s/intelligent-forest-trk85
