### ISSUE TITLE
ReactTether TS namespace appears to be empty when trying to use its types/interfaces

### ISSUE THREAD

**Issue by yurigenin** [danreeves/react-tether#223]
I'm trying to use some TS types from react-tether but VSCode does not see them:

![image](https://user-images.githubusercontent.com/11202960/81986760-aec69f00-95f5-11ea-8e5d-de247e662a05.png)

I'm trying to use Constraints type:

![image](https://user-images.githubusercontent.com/11202960/81987136-547a0e00-95f6-11ea-9318-747460ad5245.png)

But when I go to the type declaration I can see the type:

![image](https://user-images.githubusercontent.com/11202960/81987271-88553380-95f6-11ea-9cf0-a643f2e95cb6.png)

Can you provide an example of how to correctly use those?

Thanks!

**Comment by gohabereg** [comment]
I've faced the same issue. Types from namespace are not exported, so I can't access it in my code.

@yurigenin this workaround might help:
```
import { Component } from 'react';
import TetherComponent from 'react-tether';

/**
 * Inferring props interface
 */
type TetherProps = TetherComponent extends Component<infer P> ? P : never;

/**
 * Access any of props interfaces keys
 */
type TetherConstraints = TetherProps['constraints'];
```

**Comment by nathanbuchar** [comment]
Shame the types from the namespace aren't exported, but your code saved my butt. Thanks!

**Comment by danreeves** [comment]
Just to double check, did you have @types/tether installed? See #232
