### ISSUE TITLE
React 16 Support

### ISSUE THREAD

**Issue by alexprice1** [danreeves/react-tether#56]
Is there a timeline to add React 16 support?

**Comment by alexf101** [comment]
A quick FYI to help out other unwary souls:

We just upgraded ourselves to React 16, and noticed that refs defined on the content of react-tether nodes are no longer available to the parent node in componentDidMount.

I believe this is a side-effect of the changes around rendering for components that call ReactDOM.render within their render functions (something something portals?).

E.g. we used to have:
```
editableTooltipThatFocusContentOnMount() {
  componentDidMount() {
    this.input.focus();
 }
 render() {
    return <ReactTether ...>
      <input ref={el => this.input = el} />
    </ReactTether
  }
}
```

This no longer works, the ref won't be defined yet. Instead, you need to call focus from the ref.

Hope this helps someone...

**Comment by danreeves** [comment]
@alexprice1 Thanks for letting me know, I'll investigate when I get some time
