### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by souporserious** [danreeves/react-tether#58]
I've been pretty busy in other efforts and haven't been able to give this project the time it deserves. Please feel free to comment here if you would like to take the project over. First dibs to @rafeememon if you want it.

**Comment by iliastsangaris** [comment]
@rafeememon +1

**Comment by danreeves** [comment]
I'd be happy to lend a hand

**Comment by souporserious** [comment]
@danreeves I can transfer the repo to you, just let me know :)

**Comment by danreeves** [comment]
If no one else wants it, sure
