### ISSUE TITLE
Cannot read property position of undefined

### ISSUE THREAD

**Issue by shablenko** [danreeves/react-tether#62]
Hi, i`m using a library which depends on react tether, everything works, but i want to fix this error. 
Any ideas?

![image](https://user-images.githubusercontent.com/30347029/33888086-a827d420-df54-11e7-90f4-85b96d1ead33.png)

![image](https://user-images.githubusercontent.com/30347029/33888138-d00922e6-df54-11e7-8e35-3354a3a39aa3.png)

**Comment by danreeves** [comment]
Hey @shablenko, when `react-tether` only receives one component it destroys the instance of tether.

You can work around this error by checking if the tether instance exists before trying to use its methods.

e.g. `this.tether.getTetherInstance() && this.tether.position()`

This issue probably belongs on the library which is depending on `react-tether`.
