### ISSUE TITLE
react-tether 1.0

### ISSUE THREAD

**Issue by danreeves** [danreeves/react-tether#67]
- [x] Tests!
- [x] Use react portals
- [x] Support ES Modules & Typescript (with examples/tests)
- [x] Investigate renderElementTo not working
- [x] Typescript definitions
- [x] Prettier
- [x] Linting (xo)
- [x] Upgrade all deps!
- [x] Code coverage report
- [x] Add renovateapp/greenkeeper
- [x] Audit files published to npm
- [x] Drop bower support
- [ ] Flow types + figure out how to distribute them
- [ ] Changelog

**Comment by doronbrikman** [comment]
I created a PR for using react portals https://github.com/danreeves/react-tether/pull/69

**Comment by doronbrikman** [comment]
I investigated a little bit about the renderElementTo issue (#54).
As I understand it, the tether library has a constrain to which element the attachment should append to, it's checks whether one of the `elementTo` parents have any position other than `static`. So you can use the renderElementTo prop but if tether found out that it won't fit to it's rule he will re-append the element to the body.
An available workaround is to use the `bodyElement` prop to override this behaviour, but in some cases it will not behave as you expected, so you need to know what you are doing.

So, I suggest that maybe it will not be right to change something to fix it. Maybe just add a comment about it in the docs of this library?

I hope that I get it right and explained it properly.
@danreeves What do you thing?

**Comment by danreeves** [comment]
@doronbrikman Yep I think you're exactly right. Thanks for helping out with that 👍

**Comment by danreeves** [comment]
I've submit a PR to document `renderElementTo` better: https://github.com/danreeves/react-tether/pull/71

**Comment by danreeves** [comment]
https://github.com/danreeves/react-tether/blob/master/CHANGELOG.md#100
