### ISSUE TITLE
add "files": [ "..." ] to package.json to remove babelrc in your distributed npm

### ISSUE THREAD

**Issue by reothues** [danreeves/react-tether#77]
Is that "babel-plugin-add-module-exports" necessary? Can it be removed?

**Comment by danreeves** [comment]
`babel-plugin-add-module-exports` has already been removed in master, but hasn't been released yet. Good idea about reducing the files published to npm. 

Pull requests welcome!

**Comment by danreeves** [comment]
For references, the list of published files can be seen here: https://unpkg.com/react-tether@0.6.1/

**Comment by danreeves** [comment]
#135

**Comment by danreeves** [comment]
Closed by #135
